package com.myproject.knowledge.entity;


// import jakarta.persistence.Entity;
// import jakarta.persistence.GeneratedValue;
// import jakarta.persistence.GenerationType;
// import jakarta.persistence.Id;

/**
 * Entity for User.
 */
// @Entity
// @Table(schema = "Knowledge", name = "[User]")
// @Data

//@Entity
public class UserDetails {


    // @Id
    // @GeneratedValue(strategy = GenerationType.AUTO)
    // private Long id;
    // private String username;
    // private String email;

    // // Getters, setters, constructors... (can be generated by Lombok)
    // public Long getId() { return id; }
    // public void setId(Long id) { this.id = id; }
    // public String getName() { return username; }
    // public void setName(String name) { this.username = name; }
    // public String getEmail() { return email; }
    // public void setEmail(String email) { this.email = email; }

    // @Id
    // @GeneratedValue(generator = "uuid2")
    // @GenericGenerator(name = "uuid2", strategy = "org.hibernate.id.UUIDGenerator")
    // @Column(name = "id", updatable = false, nullable = false, columnDefinition = "uniqueidentifier")
    // @Convert(converter = UUIDConverter.class)
    // private UUID id;

    // @Column
    // private String username;

    // @Column
    // private String emailAddress;

}